services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
